### ISSUE TITLE
Latest element SDK is not working 

### ISSUE THREAD

**Issue by itjayaprakash** [Pearson-Higher-Ed/elements-sdk#117]
I was worked is  **"@pearson-components/elements-sdk": "^1.12.4",**   this version is working fine.

`import { Button } from '@pearson-components/elements-sdk/build/dist.elements-sdk';`
` <Button btnType="primary">Primary</Button> `

i was installed fresh new react app.
now i am taking latest version   "https://github.com/Pearson-Higher-Ed/elements-sdk" **version is 1.15.5** 

npm install --save @pearson-components/elements-sdk

`import { Button } from '@pearson-components/elements-sdk/build/dist.elements-sdk';`
` <Button btnType="primary">Primary</Button> `

Regards
J.Jayaprakash

**Comment by antelopeb** [comment]
@davodey -- can you investigate?

**Comment by davodey** [comment]
@itjayaprakash can you be more specific as to what's not working?  

I started a new app, pulled in elements, and everything seemed to be working as expected.  

If the button is displaying but missing the styling, you will have to add elements.css to the project, preferably to the public HTML file so all components can consume it.  

![screen shot 2018-09-04 at 8 32 13 am](https://user-images.githubusercontent.com/5407196/45041394-0dfc9f80-b01d-11e8-92c4-cffb9f39dd82.png)

**Comment by itjayaprakash** [comment]
@davodey  yes  style is not displaying the button . 

i  added the external link in index.html file now is working fine.

`<link rel="stylesheet" type="text/css" href="https://unpkg.com/@pearson-components/elements-sdk/build/css/elements.css" />`

Thanks
Team.
