### ISSUE TITLE
Table sort is not working ?

### ISSUE THREAD

**Issue by itjayaprakash** [Pearson-Higher-Ed/elements-sdk#121]
Hi Team,
                how to  sort the table, sort icon chaning  but data is not changing ! 
`https://pearson-higher-ed.github.io/elements-sdk/#/table`

search option and pagination available for this  table component.

Thanks & Regards
J.Jayaprakash

**Comment by itjayaprakash** [comment]
Hi Team,
how to sort the table, sort icon chaning but data is not changing !
https://pearson-higher-ed.github.io/elements-sdk/#/table

searc**h option** and pagination available for this table component.

Thanks & Regards
J.Jayaprakash

**Comment by mhomolak** [comment]
As specified in the docs, the table accepts a function which you would provide to do the actual sorting.
