### ISSUE TITLE
Tab underline doesn't move when window resizes

### ISSUE THREAD

**Issue by jackiejakob** [Pearson-Higher-Ed/elements-sdk#124]
See example: https://ux.pearson.com/prototypes/groupwork-glp-platform/#/student/milestone-view

When tabs are center-aligned, the underline does not stick with the text/tab button as you resize your window.

**Comment by sarahvc** [comment]
@davodey Sure! Thanks for tagging me!

**Comment by sarahvc** [comment]
@davodey @jackiejakob This issue has been resolved with the latest release. Thanks!
