### ISSUE TITLE
Update progress bar spacing

### ISSUE THREAD

**Issue by parkerpearson** [Pearson-Higher-Ed/elements-sdk#35]
We recently noticed that the spacing between the label and the progress bar wasn't fully specified in the design doc. This has been updated and is slightly different than the implementation.

Should be 8px between the label and the interior rail, looks like this can probably be achieved by changing the margin on the `.pe-progress-bar-rail` class to 8px from 10px.

**Comment by kaadams4** [comment]
Created story DES-895.

**Comment by mhomolak** [comment]
Updated and released in 1.9.0
