### ISSUE TITLE
No value attribute on inputs (Select and Text)

### ISSUE THREAD

**Issue by pglockwo** [Pearson-Higher-Ed/elements-sdk#43]
Can't set initial value of an Input, tried on Text and Select Component. Is there a way?

**Comment by StommePoes** [comment]
Hm, doesn't look like `value` is a prop. I'm thinking this would need to be added to Props. 

Do you want to ask PDA team to add this, or do you want to do a PR?

**Comment by pglockwo** [comment]
Thanks for the prompt reply. I will have a go at doing a pull request, if I have trouble I will get the PDA team to do it. Thanks

**Comment by StommePoes** [comment]
Cool!
