### ISSUE TITLE
How about using the elements css as an external dependency rather duplicating

### ISSUE THREAD

**Issue by dinukadesilva** [Pearson-Higher-Ed/elements-sdk#6]
@wyseguyonline @mhomolak 
I would like to suggest that we should remove this styles folder https://github.com/Pearson-Higher-Ed/elements-sdk/tree/master/src/styles and use https://github.com/Pearson-Higher-Ed/elements as an external dependency.

This would,

- Minimize the duplication
- Keep updated the elements css as well.
- Since element-sdk is going to be react specific this suggestion would keep the things clear to both react and non react users.

Regards,
@dinukadesilva

**Comment by StommePoes** [comment]
I asked. According to Jon, that elements repo will age and die. It won't get updated. Meaning everyone, whether they just want styles, or also components, all go to this repo.

**Comment by wyseguyonline** [comment]
There won't be any duplication.  Elements and Compounds have reached end of life and won't be updated apart from an extreme situation.  

The purpose of this merger is to create a single dependency for our SDK code while still providing the artifacts necessary to allow application teams to import as much or as little as they need.  This isn't unlike what Bootstrap and other libraries do in delivering a single CSS artifact and an optional JS piece to go with it.
