### ISSUE TITLE
README fails to explain how to run demos

### ISSUE THREAD

**Issue by whatevers** [Pearson-Higher-Ed/elements-sdk#99]
Despite the repo containing a suite of demos and example code that a developer can easily copy, there are no instructions about running the demo in the README.

**Comment by whatevers** [comment]
Steps to run the demo are:

git clone https://github.com/Pearson-Higher-Ed/elements-sdk.git
cd elements-sdk
npm install
npm run build
npm start

Then point the browser to http://0.0.0.0:8081/demo#/

**Comment by antelopeb** [comment]
@whatevers -- this is covered under "Contributions". You can also just run `npm start` and get to the same place.
